version: '3.8'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./getting-started-app:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    restart: unless-stopped
    
  # Optional: Add a database service if needed
  # database:
  #   image: sqlite:latest
  #   volumes:
  #     - ./data:/data
  #   restart: unless-stopped
